# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro_academico', '0005_auto_20170303_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='pre_inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_identificacion', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('tel_contacto', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sol_examen', models.BooleanField()),
                ('edad', models.IntegerField()),
                ('estado_inscripcion', models.BooleanField()),
                ('discapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Discapacidad')),
                ('edad_clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Edad')),
                ('tipo_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Identificacion')),
            ],
        ),
    ]
