# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinscripcion_examen',
            name='citacion_enviada',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
