# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_preinscripcion_examen_citacion_enviada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinscripcion_examen',
            name='nota',
            field=models.IntegerField(null=True),
        ),
    ]
