# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_auto_20170306_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_inscripcion',
            name='cita_creada',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
