# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_pre_inscripcion_cita_creada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_inscripcion',
            name='email_acudiente',
            field=models.EmailField(default='prueba@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_inscripcion',
            name='nombre_acudiente',
            field=models.CharField(default='daniel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_inscripcion',
            name='ocupacion_acudiente',
            field=models.CharField(default='prueba', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pre_inscripcion',
            name='telefono_acudiente',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
