# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0002_auto_20170303_2118'),
        ('inscripcion', '0005_auto_20170307_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_examen', models.BooleanField()),
                ('estado_inscripcion', models.BooleanField()),
                ('cita_examen_creada', models.BooleanField()),
                ('ciclo_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Ciclo')),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_identificacion', models.IntegerField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('tel_contacto', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('mayor_de_edad', models.BooleanField()),
                ('nombre_acudiente', models.CharField(max_length=50)),
                ('ocupacion_acudiente', models.CharField(max_length=50)),
                ('telefono_acudiente', models.IntegerField()),
                ('email_acudiente', models.EmailField(max_length=254)),
                ('discapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Discapacidad')),
                ('tipo_identificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Identificacion')),
            ],
        ),
        migrations.RemoveField(
            model_name='pre_inscripcion',
            name='discapacidad',
        ),
        migrations.RemoveField(
            model_name='pre_inscripcion',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='pre_inscripcion',
            name='tipo_identificacion',
        ),
        migrations.RemoveField(
            model_name='preinscripcion_examen',
            name='citacion',
        ),
        migrations.RemoveField(
            model_name='preinscripcion_examen',
            name='usuario_preinscrito',
        ),
        migrations.DeleteModel(
            name='pre_inscripcion',
        ),
        migrations.DeleteModel(
            name='preinscripcion_examen',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Persona'),
        ),
    ]
