# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0006_auto_20170309_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email_acudiente',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_acudiente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ocupacion_acudiente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono_acudiente',
            field=models.IntegerField(null=True),
        ),
    ]
