# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0008_persona_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tel_contacto',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono_acudiente',
            field=models.BigIntegerField(default=3165770904),
            preserve_default=False,
        ),
    ]
