# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0010_auto_20170310_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono_acudiente',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
