# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0012_solicitud_continuacione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_continuacione',
            name='ciclo_academico',
        ),
    ]
