# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0010_auto_20170310_1651'),
        ('inscripcion', '0014_auto_20170315_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion_Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(null=True)),
                ('citacion_enviada', models.BooleanField()),
                ('citacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Citacion')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Inscripcion')),
            ],
        ),
    ]
