# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0016_auto_20170321_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
    ]
