# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0017_remove_persona_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 19, 55, 41, 963013, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
