# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0018_persona_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='ciclo_academico',
        ),
    ]
