# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 17:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0019_remove_inscripcion_ciclo_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='num_identificacion',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
