# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0021_auto_20170323_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='num_identificacion',
            field=models.BigIntegerField(),
        ),
    ]
