# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0022_auto_20170323_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='email_acudiente',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ocupacion_acudiente',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono_acudiente',
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_acudiente',
            field=models.CharField(default='prueba', max_length=50),
            preserve_default=False,
        ),
    ]
