# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripcion', '0025_auto_20170324_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email_acudiente',
            field=models.EmailField(default='prueba@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre_acudiente',
            field=models.CharField(default='daniel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono_acudiente',
            field=models.BigIntegerField(default=31534312),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
