# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0029_persona_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Genero'),
            preserve_default=False,
        ),
    ]
