# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0030_auto_20170324_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='numero_consignacion',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
