# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0031_persona_numero_consignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='idioma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Idioma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Persona'),
            preserve_default=False,
        ),
    ]
