# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0032_auto_20170327_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_cedula', models.FileField(upload_to='imagenes/di/')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Persona')),
            ],
        ),
    ]
