# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0034_auto_20170327_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='persona',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion_examen',
            name='citacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Citacion'),
        ),
        migrations.AlterField(
            model_name='inscripcion_examen',
            name='inscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Inscripcion'),
        ),
    ]
