# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0036_auto_20170327_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Identificacion'),
            preserve_default=False,
        ),
    ]
