# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0038_auto_20170328_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion_examen',
            name='nivel_sugerido',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Nivel'),
        ),
    ]
