# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0040_auto_20170328_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion_examen',
            name='nota',
            field=models.FloatField(null=True),
        ),
    ]
