# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0041_auto_20170331_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion_examen',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
