# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0043_auto_20170403_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='numero_consignacion',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
