# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0044_persona_numero_consignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='numero_consignacion',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Persona'),
        ),
    ]
