# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0045_auto_20170405_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='numero_consignacion',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
