# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0025_auto_20170417_2004'),
        ('inscripcion', '0046_auto_20170405_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='franja',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Franja'),
            preserve_default=False,
        ),
    ]
