# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='salon',
            field=models.CharField(max_length=50),
        ),
    ]
