# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0002_auto_20170303_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
