# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0002_auto_20170302_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='Periodo_Academico',
            new_name='Ciclo',
        ),
    ]
