# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0003_auto_20170302_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Ciclo')),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Idioma')),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Jornada')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Nivel')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Sede')),
            ],
        ),
    ]
