# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0004_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='nota',
            field=models.IntegerField(null=True),
        ),
    ]
