# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0004_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_edad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=4)),
            ],
        ),
        migrations.RenameField(
            model_name='jornada',
            old_name='descripcion',
            new_name='descripcion_jornada',
        ),
    ]
