# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0006_auto_20170309_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='estado_ciclo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
