# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0011_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidad',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
