# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0012_auto_20170404_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='edad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Edad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citacion',
            name='fecha_examen',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='idioma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Idioma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citacion',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Sede'),
            preserve_default=False,
        ),
    ]
