# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0016_auto_20170411_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacion',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
