# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0018_auto_20170417_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='franja',
            name='edad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Edad'),
            preserve_default=False,
        ),
    ]
