# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0019_franja_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='jornada',
        ),
        migrations.DeleteModel(
            name='Jornada',
        ),
    ]
