# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0020_auto_20170417_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='franja',
            field=models.ManyToManyField(blank=True, to='registro_academico.Franja'),
        ),
    ]
