# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0021_idioma_franja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Semana')),
            ],
        ),
        migrations.RemoveField(
            model_name='franja',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='franja',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='franja',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='franja',
        ),
        migrations.AddField(
            model_name='franja',
            name='nombre',
            field=models.CharField(default='nombre', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idioma',
            name='franjas',
            field=models.ManyToManyField(to='registro_academico.Franja'),
        ),
        migrations.AddField(
            model_name='franja',
            name='horarios',
            field=models.ManyToManyField(to='registro_academico.Horario'),
        ),
    ]
