# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0022_auto_20170417_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franja',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='franja',
            name='horarios',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='franjas',
        ),
        migrations.DeleteModel(
            name='Franja',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
