# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_academico', '0023_auto_20170417_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Edad')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_academico.Semana')),
            ],
        ),
        migrations.AddField(
            model_name='franja',
            name='horarios',
            field=models.ManyToManyField(to='registro_academico.Horario'),
        ),
        migrations.AddField(
            model_name='idioma',
            name='franjas',
            field=models.ManyToManyField(to='registro_academico.Franja'),
        ),
    ]
